@echo off
set "PATH=%PATH%;C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\Program Files (x86)\Git\cmd;C:\Users\%USERNAME%\AppData\Local\Programs\Git\cmd"

echo Adding changes...
git add .
echo Committing...
git commit -m "Fix: Upgrade google-generativeai to >=0.8.3 and simplify model string"
echo Pushing...
git push
